--- 
- 
  become: true
  hosts: all
  name: Deploy
  tasks: 
    - 
      copy: "src=/home/runner/work/tomcat_java_maven/tomcat_java_maven/target/WebApp-pipeline.war dest='http://{{user_name}}:{{password}}@3.109.201.248:8080//manager/text/deploy?path=/web_aapp&update=true'"
      name: "Deploy to Tomcat"
  vars_file: 
    - tomcat_u_p.yml

